package cmd

var (
	cmdGroupGeneric      = "generic"
	cmdGroupString       = "string"
	cmdGroupList         = "list"
	cmdGroupSet          = "set"
	cmdGroupSortedSet    = "sorted_set"
	cmdGroupHash         = "hash"
	cmdGroupPubSub       = "pubsub"
	cmdGroupTransactions = "transactions"
	cmdGroupConnection   = "connection"
	cmdGroupServer       = "server"
	cmdGroupScripting    = "scripting"
	cmdGroupHyperloglog  = "hyperloglog"
	cmdGroupCluster      = "cluster"
	cmdGroupGeo          = "geo"
	cmdGroupStream       = "stream"
)

type CommandHelp struct {
	Name    string
	Params  string
	Summary string
	Group   string
	Since   string
}

var CommandHelps = CaseMap{
	"ACL CAT": {"ACL CAT",
		"[categoryname]",
		"List the ACL categories or the commands inside a category",
		cmdGroupServer,
		"6.0.0"},
	"ACL DELUSER": {"ACL DELUSER",
		"username [username ...]",
		"Remove the specified ACL users and the associated rules",
		cmdGroupServer,
		"6.0.0"},
	"ACL GENPASS": {"ACL GENPASS",
		"[bits]",
		"Generate a pseudorandom secure password to use for ACL users",
		cmdGroupServer,
		"6.0.0"},
	"ACL HELP": {"ACL HELP",
		"-",
		"Show helpful text about the different subcommands",
		cmdGroupServer,
		"6.0.0"},
	"ACL LIST": {"ACL LIST",
		"-",
		"List the current ACL rules in ACL config file format",
		cmdGroupServer,
		"6.0.0"},
	"ACL LOAD": {"ACL LOAD",
		"-",
		"Reload the ACLs from the configured ACL file",
		cmdGroupServer,
		"6.0.0"},
	"ACL LOG": {"ACL LOG",
		"[count or RESET]",
		"List latest events denied because of ACLs in place",
		cmdGroupServer,
		"6.0.0"},
	"ACL SAVE": {"ACL SAVE",
		"-",
		"Save the current ACL rules in the configured ACL file",
		cmdGroupServer,
		"6.0.0"},
	"ACL SETUSER": {"ACL SETUSER",
		"username [rule [rule ...]]",
		"Modify or create the rules for a specific ACL user",
		cmdGroupServer,
		"6.0.0"},
	"ACL USERS": {"ACL USERS",
		"-",
		"List the username of all the configured ACL rules",
		cmdGroupServer,
		"6.0.0"},
	"ACL WHOAMI": {"ACL WHOAMI",
		"-",
		"Return the name of the user associated to the current connection",
		cmdGroupServer,
		"6.0.0"},
	"APPEND": {"APPEND",
		"key value",
		"Append a value to a key",
		cmdGroupString,
		"2.0.0"},
	"AUTH": {"AUTH",
		"username password",
		"Authenticate to the server",
		cmdGroupConnection,
		"1.0.0"},
	"BGREWRITEAOF": {"BGREWRITEAOF",
		"-",
		"Asynchronously rewrite the append-only file",
		cmdGroupServer,
		"1.0.0"},
	"BGSAVE": {
		"BGSAVE",
		"[SCHEDULE]",
		"Asynchronously save the dataset to disk",
		cmdGroupServer,
		"1.0.0"},
	"BITCOUNT": {"BITCOUNT",
		"key [start end]",
		"Count set bits in a string",
		cmdGroupString,
		"2.6.0"},
	"BITFIELD": {"BITFIELD",
		"key [GET type offset] [SET type offset value] [INCRBY type offset increment] [OVERFLOW WRAP|SAT|FAIL]",
		"Perform arbitrary bitfield integer operations on strings",
		cmdGroupString,
		"3.2.0"},
	"BITOP": {"BITOP",
		"operation destkey key [key ...]",
		"Perform bitwise operations between strings",
		cmdGroupString,
		"2.6.0"},
	"BITPOS": {"BITPOS",
		"key bit [start] [end]",
		"Find first bit set or clear in a string",
		cmdGroupString,
		"2.8.7"},
	"BLPOP": {"BLPOP",
		"key [key ...] timeout",
		"Remove and get the first element in a list, or block until one is available",
		cmdGroupList,
		"2.0.0"},
	"BRPOP": {"BRPOP",
		"key [key ...] timeout",
		"Remove and get the last element in a list, or block until one is available",
		cmdGroupList,
		"2.0.0"},
	"BRPOPLPUSH": {"BRPOPLPUSH",
		"source destination timeout",
		"Pop an element from a list, push it to another list and return it; or block until one is available",
		cmdGroupList,
		"2.2.0"},
	"BZPOPMAX": {"BZPOPMAX",
		"key [key ...] timeout",
		"Remove and return the member with the highest score from one or more sorted sets, or block until one is available",
		cmdGroupSortedSet,
		"5.0.0"},
	"BZPOPMIN": {"BZPOPMIN",
		"key [key ...] timeout",
		"Remove and return the member with the lowest score from one or more sorted sets, or block until one is available",
		cmdGroupSortedSet,
		"5.0.0"},
	"CLIENT CACHING": {"CLIENT CACHING",
		"YES|NO",
		"Instruct the server about tracking or not keys in the next request",
		cmdGroupConnection,
		"6.0.0"},
	"CLIENT GETNAME": {"CLIENT GETNAME",
		"-",
		"Get the current connection name",
		cmdGroupConnection,
		"2.6.9"},
	"CLIENT GETREDIR": {"CLIENT GETREDIR",
		"-",
		"Get tracking notifications redirection client ID if any",
		cmdGroupConnection,
		"6.0.0"},
	"CLIENT ID": {"CLIENT ID",
		"-",
		"Returns the client ID for the current connection",
		cmdGroupConnection,
		"5.0.0"},
	"CLIENT KILL": {"CLIENT KILL",
		"[ip:port] [ID client-id] [TYPE normal|master|slave|pubsub] [USER username] [ADDR ip:port] [SKIPME yes/no]",
		"Kill the connection of a client",
		cmdGroupConnection,
		"2.4.0"},
	"CLIENT LIST": {"CLIENT LIST",
		"[TYPE normal|master|replica|pubsub]",
		"Get the list of client connections",
		cmdGroupConnection,
		"2.4.0"},
	"CLIENT PAUSE": {"CLIENT PAUSE",
		"timeout",
		"Stop processing commands from clients for some time",
		cmdGroupConnection,
		"2.9.50"},
	"CLIENT REPLY": {"CLIENT REPLY",
		"ON|OFF|SKIP",
		"Instruct the server whether to reply to commands",
		cmdGroupConnection,
		"3.2.0"},
	"CLIENT SETNAME": {"CLIENT SETNAME",
		"connection-name",
		"Set the current connection name",
		cmdGroupConnection,
		"2.6.9"},
	"CLIENT TRACKING": {"CLIENT TRACKING",
		"ON|OFF [REDIRECT client-id] [PREFIX prefix [PREFIX prefix ...]] [BCAST] [OPTIN] [OPTOUT] [NOLOOP]",
		"Enable or disable server assisted client side caching support",
		cmdGroupConnection,
		"6.0.0"},
	"CLIENT UNBLOCK": {"CLIENT UNBLOCK",
		"client-id [TIMEOUT|ERROR]",
		"Unblock a client blocked in a blocking command from a different connection",
		cmdGroupConnection,
		"5.0.0"},
	"CLUSTER ADDSLOTS": {"CLUSTER ADDSLOTS",
		"slot [slot ...]",
		"Assign new hash slots to receiving node",
		cmdGroupCluster,
		"3.0.0"},
	"CLUSTER BUMPEPOCH": {"CLUSTER BUMPEPOCH",
		"-",
		"Advance the cluster config epoch",
		cmdGroupCluster,
		"3.0.0"},
	"CLUSTER COUNT-FAILURE-REPORTS": {"CLUSTER COUNT-FAILURE-REPORTS",
		"node-id",
		"Return the number of failure reports active for a given node",
		cmdGroupCluster,
		"3.0.0"},
	"CLUSTER COUNTKEYSINSLOT": {"CLUSTER COUNTKEYSINSLOT",
		"slot",
		"Return the number of local keys in the specified hash slot",
		cmdGroupCluster,
		"3.0.0"},
	"CLUSTER DELSLOTS": {"CLUSTER DELSLOTS",
		"slot [slot ...]",
		"Set hash slots as unbound in receiving node",
		cmdGroupCluster,
		"3.0.0"},
	"CLUSTER FAILOVER": {"CLUSTER FAILOVER",
		"[FORCE|TAKEOVER]",
		"Forces a replica to perform a manual failover of its master.",
		cmdGroupCluster,
		"3.0.0"},
	"CLUSTER FLUSHSLOTS": {"CLUSTER FLUSHSLOTS",
		"-",
		"Delete a node's own slots information",
		cmdGroupCluster,
		"3.0.0"},
	"CLUSTER FORGET": {"CLUSTER FORGET",
		"node-id",
		"Remove a node from the nodes table",
		cmdGroupCluster,
		"3.0.0"},
	"CLUSTER GETKEYSINSLOT": {"CLUSTER GETKEYSINSLOT",
		"slot count",
		"Return local key names in the specified hash slot",
		cmdGroupCluster,
		"3.0.0"},
	"CLUSTER INFO": {"CLUSTER INFO",
		"-",
		"Provides info about Redis Cluster node state",
		cmdGroupCluster,
		"3.0.0"},
	"CLUSTER KEYSLOT": {"CLUSTER KEYSLOT",
		"key",
		"Returns the hash slot of the specified key",
		cmdGroupCluster,
		"3.0.0"},
	"CLUSTER MEET": {"CLUSTER MEET",
		"ip port",
		"Force a node cluster to handshake with another node",
		cmdGroupCluster,
		"3.0.0"},
	"CLUSTER MYID": {"CLUSTER MYID",
		"-",
		"Return the node id",
		cmdGroupCluster,
		"3.0.0"},
	"CLUSTER NODES": {"CLUSTER NODES",
		"-",
		"Get Cluster config for the node",
		cmdGroupCluster,
		"3.0.0"},
	"CLUSTER REPLICAS": {"CLUSTER REPLICAS",
		"node-id",
		"List replica nodes of the specified master node",
		cmdGroupCluster,
		"5.0.0"},
	"CLUSTER REPLICATE": {"CLUSTER REPLICATE",
		"node-id",
		"Reconfigure a node as a replica of the specified master node",
		cmdGroupCluster,
		"3.0.0"},
	"CLUSTER RESET": {"CLUSTER RESET",
		"[HARD|SOFT]",
		"Reset a Redis Cluster node",
		cmdGroupCluster,
		"3.0.0"},
	"CLUSTER SAVECONFIG": {"CLUSTER SAVECONFIG",
		"-",
		"Forces the node to save cluster state on disk",
		cmdGroupCluster,
		"3.0.0"},
	"CLUSTER SET-CONFIG-EPOCH": {"CLUSTER SET-CONFIG-EPOCH",
		"config-epoch",
		"Set the configuration epoch in a new node",
		cmdGroupCluster,
		"3.0.0"},
	"CLUSTER SETSLOT": {"CLUSTER SETSLOT",
		"slot IMPORTING|MIGRATING|STABLE|NODE [node-id]",
		"Bind a hash slot to a specific node",
		cmdGroupCluster,
		"3.0.0"},
	"CLUSTER SLAVES": {"CLUSTER SLAVES",
		"node-id",
		"List replica nodes of the specified master node",
		cmdGroupCluster,
		"3.0.0"},
	"CLUSTER SLOTS": {"CLUSTER SLOTS",
		"-",
		"Get array of Cluster slot to node mappings",
		cmdGroupCluster,
		"3.0.0"},
	"COMMAND": {"COMMAND",
		"-",
		"Get array of Redis command details",
		cmdGroupServer,
		"2.8.13"},
	"COMMAND COUNT": {"COMMAND COUNT",
		"-",
		"Get total number of Redis commands",
		cmdGroupServer,
		"2.8.13"},
	"COMMAND GETKEYS": {"COMMAND GETKEYS",
		"-",
		"Extract keys given a full Redis command",
		cmdGroupServer,
		"2.8.13"},
	"COMMAND INFO": {"COMMAND INFO",
		"command-name [command-name ...]",
		"Get array of specific Redis command details",
		cmdGroupServer,
		"2.8.13"},
	"CONFIG GET": {"CONFIG GET",
		"parameter",
		"Get the value of a configuration parameter",
		cmdGroupServer,
		"2.0.0"},
	"CONFIG RESETSTAT": {"CONFIG RESETSTAT",
		"-",
		"Reset the stats returned by INFO",
		cmdGroupServer,
		"2.0.0"},
	"CONFIG REWRITE": {"CONFIG REWRITE",
		"-",
		"Rewrite the configuration file with the in memory configuration",
		cmdGroupServer,
		"2.8.0"},
	"CONFIG SET": {"CONFIG SET",
		"parameter value",
		"Set a configuration parameter to the given value",
		cmdGroupServer,
		"2.0.0"},
	"DBSIZE": {"DBSIZE",
		"-",
		"Return the number of keys in the selected database",
		cmdGroupServer,
		"1.0.0"},
	"DEBUG OBJECT": {"DEBUG OBJECT",
		"key",
		"Get debugging information about a key",
		cmdGroupServer,
		"1.0.0"},
	"DEBUG SEGFAULT": {"DEBUG SEGFAULT",
		"-",
		"Make the server crash",
		cmdGroupServer,
		"1.0.0"},
	"DECR": {"DECR",
		"key",
		"Decrement the integer value of a key by one",
		cmdGroupString,
		"1.0.0"},
	"DECRBY": {"DECRBY",
		"key decrement",
		"Decrement the integer value of a key by the given number",
		cmdGroupString,
		"1.0.0"},
	"DEL": {"DEL",
		"key [key ...]",
		"Delete a key",
		cmdGroupGeneric,
		"1.0.0"},
	"DISCARD": {"DISCARD",
		"-",
		"Discard all commands issued after MULTI",
		cmdGroupTransactions,
		"2.0.0"},
	"DUMP": {"DUMP",
		"key",
		"Return a serialized version of the value stored at the specified key.",
		cmdGroupGeneric,
		"2.6.0"},
	"ECHO": {"ECHO",
		"message",
		"Echo the given string",
		cmdGroupConnection,
		"1.0.0"},
	"EVAL": {"EVAL",
		"script numkeys key [key ...] arg [arg ...]",
		"Execute a Lua script server side",
		cmdGroupScripting,
		"2.6.0"},
	"EVALSHA": {"EVALSHA",
		"sha1 numkeys key [key ...] arg [arg ...]",
		"Execute a Lua script server side",
		cmdGroupScripting,
		"2.6.0"},
	"EXEC": {"EXEC",
		"-",
		"Execute all commands issued after MULTI",
		cmdGroupTransactions,
		"1.2.0"},
	"EXISTS": {"EXISTS",
		"key [key ...]",
		"Determine if a key exists",
		cmdGroupGeneric,
		"1.0.0"},
	"EXPIRE": {"EXPIRE",
		"key seconds",
		"Set a key's time to live in seconds",
		cmdGroupGeneric,
		"1.0.0"},
	"EXPIREAT": {"EXPIREAT",
		"key timestamp",
		"Set the expiration for a key as a UNIX timestamp",
		cmdGroupGeneric,
		"1.2.0"},
	"FLUSHALL": {"FLUSHALL",
		"[ASYNC]",
		"Remove all keys from all databases",
		cmdGroupServer,
		"1.0.0"},
	"FLUSHDB": {"FLUSHDB",
		"[ASYNC]",
		"Remove all keys from the current database",
		cmdGroupServer,
		"1.0.0"},
	"GEOADD": {"GEOADD",
		"key longitude latitude member [longitude latitude member ...]",
		"Add one or more geospatial items in the geospatial index represented using a sorted set",
		cmdGroupGeo,
		"3.2.0"},
	"GEODIST": {"GEODIST",
		"key member1 member2 [m|km|ft|mi]",
		"Returns the distance between two members of a geospatial index",
		cmdGroupGeo,
		"3.2.0"},
	"GEOHASH": {"GEOHASH",
		"key member [member ...]",
		"Returns members of a geospatial index as standard geohash strings",
		cmdGroupGeo,
		"3.2.0"},
	"GEOPOS": {"GEOPOS",
		"key member [member ...]",
		"Returns longitude and latitude of members of a geospatial index",
		cmdGroupGeo,
		"3.2.0"},
	"GEORADIUS": {"GEORADIUS",
		"key longitude latitude radius m|km|ft|mi [WITHCOORD] [WITHDIST] [WITHHASH] [COUNT count] [ASC|DESC] [STORE key] [STOREDIST key]",
		"Query a sorted set representing a geospatial index to fetch members matching a given maximum distance from a point",
		cmdGroupGeo,
		"3.2.0"},
	"GEORADIUSBYMEMBER": {"GEORADIUSBYMEMBER",
		"key member radius m|km|ft|mi [WITHCOORD] [WITHDIST] [WITHHASH] [COUNT count] [ASC|DESC] [STORE key] [STOREDIST key]",
		"Query a sorted set representing a geospatial index to fetch members matching a given maximum distance from a member",
		cmdGroupGeo,
		"3.2.0"},
	"GET": {"GET",
		"key",
		"Get the value of a key",
		cmdGroupString,
		"1.0.0"},
	"GETBIT": {"GETBIT",
		"key offset",
		"Returns the bit value at offset in the string value stored at key",
		cmdGroupString,
		"2.2.0"},
	"GETRANGE": {"GETRANGE",
		"key start end",
		"Get a substring of the string stored at a key",
		cmdGroupString,
		"2.4.0"},
	"GETSET": {"GETSET",
		"key value",
		"Set the string value of a key and return its old value",
		cmdGroupString,
		"1.0.0"},
	"HDEL": {"HDEL",
		"key field [field ...]",
		"Delete one or more hash fields",
		cmdGroupHash,
		"2.0.0"},
	"HELLO": {"HELLO",
		"protover [AUTH username password] [SETNAME clientname]",
		"switch Redis protocol",
		cmdGroupConnection,
		"6.0.0"},
	"HEXISTS": {"HEXISTS",
		"key field",
		"Determine if a hash field exists",
		cmdGroupHash,
		"2.0.0"},
	"HGET": {"HGET",
		"key field",
		"Get the value of a hash field",
		cmdGroupHash,
		"2.0.0"},
	"HGETALL": {"HGETALL",
		"key",
		"Get all the fields and values in a hash",
		cmdGroupHash,
		"2.0.0"},
	"HINCRBY": {"HINCRBY",
		"key field increment",
		"Increment the integer value of a hash field by the given number",
		cmdGroupHash,
		"2.0.0"},
	"HINCRBYFLOAT": {"HINCRBYFLOAT",
		"key field increment",
		"Increment the float value of a hash field by the given amount",
		cmdGroupHash,
		"2.6.0"},
	"HKEYS": {"HKEYS",
		"key",
		"Get all the fields in a hash",
		cmdGroupHash,
		"2.0.0"},
	"HLEN": {"HLEN",
		"key",
		"Get the number of fields in a hash",
		cmdGroupHash,
		"2.0.0"},
	"HMGET": {"HMGET",
		"key field [field ...]",
		"Get the values of all the given hash fields",
		cmdGroupHash,
		"2.0.0"},
	"HMSET": {"HMSET",
		"key field value [field value ...]",
		"Set multiple hash fields to multiple values",
		cmdGroupHash,
		"2.0.0"},
	"HSCAN": {"HSCAN",
		"key cursor [MATCH pattern] [COUNT count]",
		"Incrementally iterate hash fields and associated values",
		cmdGroupHash,
		"2.8.0"},
	"HSET": {"HSET",
		"key field value [field value ...]",
		"Set the string value of a hash field",
		cmdGroupHash,
		"2.0.0"},
	"HSETNX": {"HSETNX",
		"key field value",
		"Set the value of a hash field, only if the field does not exist",
		cmdGroupHash,
		"2.0.0"},
	"HSTRLEN": {"HSTRLEN",
		"key field",
		"Get the length of the value of a hash field",
		cmdGroupHash,
		"3.2.0"},
	"HVALS": {"HVALS",
		"key",
		"Get all the values in a hash",
		cmdGroupHash,
		"2.0.0"},
	"INCR": {"INCR",
		"key",
		"Increment the integer value of a key by one",
		cmdGroupString,
		"1.0.0"},
	"INCRBY": {"INCRBY",
		"key increment",
		"Increment the integer value of a key by the given amount",
		cmdGroupString,
		"1.0.0"},
	"INCRBYFLOAT": {"INCRBYFLOAT",
		"key increment",
		"Increment the float value of a key by the given amount",
		cmdGroupString,
		"2.6.0"},
	"INFO": {"INFO",
		"[section]",
		"Get information and statistics about the server",
		cmdGroupServer,
		"1.0.0"},
	"KEYS": {"KEYS",
		"pattern",
		"Find all keys matching the given pattern",
		cmdGroupGeneric,
		"1.0.0"},
	"LASTSAVE": {"LASTSAVE",
		"-",
		"Get the UNIX time stamp of the last successful save to disk",
		cmdGroupServer,
		"1.0.0"},
	"LATENCY DOCTOR": {"LATENCY DOCTOR",
		"-",
		"Return a human readable latency analysis report.",
		cmdGroupServer,
		"2.8.13"},
	"LATENCY GRAPH": {"LATENCY GRAPH",
		"event",
		"Return a latency graph for the event.",
		cmdGroupServer,
		"2.8.13"},
	"LATENCY HELP": {"LATENCY HELP",
		"-",
		"Show helpful text about the different subcommands.",
		cmdGroupServer,
		"2.8.13"},
	"LATENCY HISTORY": {"LATENCY HISTORY",
		"event",
		"Return timestamp-latency samples for the event.",
		cmdGroupServer,
		"2.8.13"},
	"LATENCY LATEST": {"LATENCY LATEST",
		"-",
		"Return the latest latency samples for all events.",
		cmdGroupServer,
		"2.8.13"},
	"LATENCY RESET": {"LATENCY RESET",
		"[event [event ...]]",
		"Reset latency data for one or more events.",
		cmdGroupServer,
		"2.8.13"},
	"LINDEX": {"LINDEX",
		"key index",
		"Get an element from a list by its index",
		cmdGroupList,
		"1.0.0"},
	"LINSERT": {"LINSERT",
		"key BEFORE|AFTER pivot element",
		"Insert an element before or after another element in a list",
		cmdGroupList,
		"2.2.0"},
	"LLEN": {"LLEN",
		"key",
		"Get the length of a list",
		cmdGroupList,
		"1.0.0"},
	"LOLWUT": {"LOLWUT",
		"[VERSION version]",
		"Display some computer art and the Redis version",
		cmdGroupServer,
		"5.0.0"},
	"LPOP": {"LPOP",
		"key",
		"Remove and get the first element in a list",
		cmdGroupList,
		"1.0.0"},
	"LPOS": {"LPOS",
		"key element [FIRST rank] [COUNT num-matches] [MAXLEN len]",
		"Return the index of matching elements on a list",
		cmdGroupList,
		"6.0.6"},
	"LPUSH": {"LPUSH",
		"key element [element ...]",
		"Prepend one or multiple elements to a list",
		cmdGroupList,
		"1.0.0"},
	"LPUSHX": {"LPUSHX",
		"key element [element ...]",
		"Prepend an element to a list, only if the list exists",
		cmdGroupList,
		"2.2.0"},
	"LRANGE": {"LRANGE",
		"key start stop",
		"Get a range of elements from a list",
		cmdGroupList,
		"1.0.0"},
	"LREM": {"LREM",
		"key count element",
		"Remove elements from a list",
		cmdGroupList,
		"1.0.0"},
	"LSET": {"LSET",
		"key index element",
		"Set the value of an element in a list by its index",
		cmdGroupList,
		"1.0.0"},
	"LTRIM": {"LTRIM",
		"key start stop",
		"Trim a list to the specified range",
		cmdGroupList,
		"1.0.0"},
	"MEMORY DOCTOR": {"MEMORY DOCTOR",
		"-",
		"Outputs memory problems report",
		cmdGroupServer,
		"4.0.0"},
	"MEMORY HELP": {"MEMORY HELP",
		"-",
		"Show helpful text about the different subcommands",
		cmdGroupServer,
		"4.0.0"},
	"MEMORY MALLOC-STATS": {"MEMORY MALLOC-STATS",
		"-",
		"Show allocator internal stats",
		cmdGroupServer,
		"4.0.0"},
	"MEMORY PURGE": {"MEMORY PURGE",
		"-",
		"Ask the allocator to release memory",
		cmdGroupServer,
		"4.0.0"},
	"MEMORY STATS": {"MEMORY STATS",
		"-",
		"Show memory usage details",
		cmdGroupServer,
		"4.0.0"},
	"MEMORY USAGE": {"MEMORY USAGE",
		"key [SAMPLES count]",
		"Estimate the memory usage of a key",
		cmdGroupServer,
		"4.0.0"},
	"MGET": {"MGET",
		"key [key ...]",
		"Get the values of all the given keys",
		cmdGroupString,
		"1.0.0"},
	"MIGRATE": {"MIGRATE",
		"host port key| destination-db timeout [COPY] [REPLACE] [AUTH password] [KEYS key]",
		"Atomically transfer a key from a Redis instance to another one.",
		cmdGroupGeneric,
		"2.6.0"},
	"MODULE LIST": {"MODULE LIST",
		"-",
		"List all modules loaded by the server",
		cmdGroupServer,
		"4.0.0"},
	"MODULE LOAD": {"MODULE LOAD",
		"path [arg]",
		"Load a module",
		cmdGroupServer,
		"4.0.0"},
	"MODULE UNLOAD": {"MODULE UNLOAD",
		"name",
		"Unload a module",
		cmdGroupServer,
		"4.0.0"},
	"MONITOR": {"MONITOR",
		"-",
		"Listen for all requests received by the server in real time",
		cmdGroupServer,
		"1.0.0"},
	"MOVE": {"MOVE",
		"key db",
		"Move a key to another database",
		cmdGroupGeneric,
		"1.0.0"},
	"MSET": {"MSET",
		"key value [key value ...]",
		"Set multiple keys to multiple values",
		cmdGroupString,
		"1.0.1"},
	"MSETNX": {"MSETNX",
		"key value [key value ...]",
		"Set multiple keys to multiple values, only if none of the keys exist",
		cmdGroupString,
		"1.0.1"},
	"MULTI": {"MULTI",
		"-",
		"Mark the start of a transaction block",
		cmdGroupTransactions,
		"1.2.0"},
	"OBJECT": {"OBJECT",
		"subcommand [arguments [arguments ...]]",
		"Inspect the internals of Redis objects",
		cmdGroupGeneric,
		"2.2.3"},
	"PERSIST": {"PERSIST",
		"key",
		"Remove the expiration from a key",
		cmdGroupGeneric,
		"2.2.0"},
	"PEXPIRE": {"PEXPIRE",
		"key milliseconds",
		"Set a key's time to live in milliseconds",
		cmdGroupGeneric,
		"2.6.0"},
	"PEXPIREAT": {"PEXPIREAT",
		"key milliseconds-timestamp",
		"Set the expiration for a key as a UNIX timestamp specified in milliseconds",
		cmdGroupGeneric,
		"2.6.0"},
	"PFADD": {"PFADD",
		"key element [element ...]",
		"Adds the specified elements to the specified HyperLogLog.",
		cmdGroupHyperloglog,
		"2.8.9"},
	"PFCOUNT": {"PFCOUNT",
		"key [key ...]",
		"Return the approximated cardinality of the set(s) observed by the HyperLogLog at key(s).",
		cmdGroupHyperloglog,
		"2.8.9"},
	"PFMERGE": {"PFMERGE",
		"destkey sourcekey [sourcekey ...]",
		"Merge N different HyperLogLogs into a single one.",
		cmdGroupHyperloglog,
		"2.8.9"},
	"PING": {"PING",
		"[message]",
		"Ping the server",
		cmdGroupConnection,
		"1.0.0"},
	"PSETEX": {"PSETEX",
		"key milliseconds value",
		"Set the value and expiration in milliseconds of a key",
		cmdGroupString,
		"2.6.0"},
	"PSUBSCRIBE": {"PSUBSCRIBE",
		"pattern [pattern ...]",
		"Listen for messages published to channels matching the given patterns",
		cmdGroupPubSub,
		"2.0.0"},
	"PSYNC": {"PSYNC",
		"replicationid offset",
		"Internal command used for replication",
		cmdGroupServer,
		"2.8.0"},
	"PTTL": {"PTTL",
		"key",
		"Get the time to live for a key in milliseconds",
		cmdGroupGeneric,
		"2.6.0"},
	"PUBLISH": {"PUBLISH",
		"channel message",
		"Post a message to a channel",
		cmdGroupPubSub,
		"2.0.0"},
	"PUBSUB": {"PUBSUB",
		"subcommand [argument [argument ...]]",
		"Inspect the state of the Pub/Sub subsystem",
		cmdGroupPubSub,
		"2.8.0"},
	"PUNSUBSCRIBE": {"PUNSUBSCRIBE",
		"[pattern [pattern ...]]",
		"Stop listening for messages posted to channels matching the given patterns",
		cmdGroupPubSub,
		"2.0.0"},
	"QUIT": {"QUIT",
		"-",
		"Close the connection",
		cmdGroupConnection,
		"1.0.0"},
	"RANDOMKEY": {"RANDOMKEY",
		"-",
		"Return a random key from the keyspace",
		cmdGroupGeneric,
		"1.0.0"},
	"READONLY": {"READONLY",
		"-",
		"Enables read queries for a connection to a cluster replica node",
		cmdGroupCluster,
		"3.0.0"},
	"READWRITE": {"READWRITE",
		"-",
		"Disables read queries for a connection to a cluster replica node",
		cmdGroupCluster,
		"3.0.0"},
	"RENAME": {"RENAME",
		"key newkey",
		"Rename a key",
		cmdGroupGeneric,
		"1.0.0"},
	"RENAMENX": {"RENAMENX",
		"key newkey",
		"Rename a key, only if the new key does not exist",
		cmdGroupGeneric,
		"1.0.0"},
	"REPLICAOF": {"REPLICAOF",
		"host port",
		"Make the server a replica of another instance, or promote it as master.",
		cmdGroupServer,
		"5.0.0"},
	"RESTORE": {"RESTORE",
		"key ttl serialized-value [REPLACE] [ABSTTL] [IDLETIME seconds] [FREQ frequency]",
		"Create a key using the provided serialized value, previously obtained using DUMP.",
		cmdGroupGeneric,
		"2.6.0"},
	"ROLE": {"ROLE",
		"-",
		"Return the role of the instance in the context of replication",
		cmdGroupServer,
		"2.8.12"},
	"RPOP": {"RPOP",
		"key",
		"Remove and get the last element in a list",
		cmdGroupList,
		"1.0.0"},
	"RPOPLPUSH": {"RPOPLPUSH",
		"source destination",
		"Remove the last element in a list, prepend it to another list and return it",
		cmdGroupList,
		"1.2.0"},
	"RPUSH": {"RPUSH",
		"key element [element ...]",
		"Append one or multiple elements to a list",
		cmdGroupList,
		"1.0.0"},
	"RPUSHX": {"RPUSHX",
		"key element [element ...]",
		"Append an element to a list, only if the list exists",
		cmdGroupList,
		"2.2.0"},
	"SADD": {"SADD",
		"key member [member ...]",
		"Add one or more members to a set",
		cmdGroupSet,
		"1.0.0"},
	"SAVE": {"SAVE",
		"-",
		"Synchronously save the dataset to disk",
		cmdGroupServer,
		"1.0.0"},
	"SCAN": {"SCAN",
		"cursor [MATCH pattern] [COUNT count] [TYPE type]",
		"Incrementally iterate the keys space",
		cmdGroupGeneric,
		"2.8.0"},
	"SCARD": {"SCARD",
		"key",
		"Get the number of members in a set",
		cmdGroupSet,
		"1.0.0"},
	"SCRIPT DEBUG": {"SCRIPT DEBUG",
		"YES|SYNC|NO",
		"Set the debug mode for executed scripts.",
		cmdGroupScripting,
		"3.2.0"},
	"SCRIPT EXISTS": {"SCRIPT EXISTS",
		"sha1 [sha1 ...]",
		"Check existence of scripts in the script cache.",
		cmdGroupScripting,
		"2.6.0"},
	"SCRIPT FLUSH": {"SCRIPT FLUSH",
		"-",
		"Remove all the scripts from the script cache.",
		cmdGroupScripting,
		"2.6.0"},
	"SCRIPT KILL": {"SCRIPT KILL",
		"-",
		"Kill the script currently in execution.",
		cmdGroupScripting,
		"2.6.0"},
	"SCRIPT LOAD": {"SCRIPT LOAD",
		"script",
		"Load the specified Lua script into the script cache.",
		cmdGroupScripting,
		"2.6.0"},
	"SDIFF": {"SDIFF",
		"key [key ...]",
		"Subtract multiple sets",
		cmdGroupSet,
		"1.0.0"},
	"SDIFFSTORE": {"SDIFFSTORE",
		"destination key [key ...]",
		"Subtract multiple sets and store the resulting set in a key",
		cmdGroupSet,
		"1.0.0"},
	"SELECT": {"SELECT",
		"index",
		"Change the selected database for the current connection",
		cmdGroupConnection,
		"1.0.0"},
	"SET": {"SET",
		"key value [EX seconds|PX milliseconds] [NX|XX] [KEEPTTL]",
		"Set the string value of a key",
		cmdGroupString,
		"1.0.0"},
	"SETBIT": {"SETBIT",
		"key offset value",
		"Sets or clears the bit at offset in the string value stored at key",
		cmdGroupString,
		"2.2.0"},
	"SETEX": {"SETEX",
		"key seconds value",
		"Set the value and expiration of a key",
		cmdGroupString,
		"2.0.0"},
	"SETNX": {"SETNX",
		"key value",
		"Set the value of a key, only if the key does not exist",
		cmdGroupString,
		"1.0.0"},
	"SETRANGE": {"SETRANGE",
		"key offset value",
		"Overwrite part of a string at key starting at the specified offset",
		cmdGroupString,
		"2.2.0"},
	"SHUTDOWN": {"SHUTDOWN",
		"[NOSAVE|SAVE]",
		"Synchronously save the dataset to disk and then shut down the server",
		cmdGroupServer,
		"1.0.0"},
	"SINTER": {"SINTER",
		"key [key ...]",
		"Intersect multiple sets",
		cmdGroupSet,
		"1.0.0"},
	"SINTERSTORE": {"SINTERSTORE",
		"destination key [key ...]",
		"Intersect multiple sets and store the resulting set in a key",
		cmdGroupSet,
		"1.0.0"},
	"SISMEMBER": {"SISMEMBER",
		"key member",
		"Determine if a given value is a member of a set",
		cmdGroupSet,
		"1.0.0"},
	"SLAVEOF": {"SLAVEOF",
		"host port",
		"Make the server a replica of another instance, or promote it as master. Deprecated starting with Redis 5. Use REPLICAOF instead.",
		cmdGroupServer,
		"1.0.0"},
	"SLOWLOG": {"SLOWLOG",
		"subcommand [argument]",
		"Manages the Redis slow queries log",
		cmdGroupServer,
		"2.2.12"},
	"SMEMBERS": {"SMEMBERS",
		"key",
		"Get all the members in a set",
		cmdGroupSet,
		"1.0.0"},
	"SMOVE": {"SMOVE",
		"source destination member",
		"Move a member from one set to another",
		cmdGroupSet,
		"1.0.0"},
	"SORT": {"SORT",
		"key [BY pattern] [LIMIT offset count] [GET pattern [GET pattern ...]] [ASC|DESC] [ALPHA] [STORE destination]",
		"Sort the elements in a list, set or sorted set",
		cmdGroupGeneric,
		"1.0.0"},
	"SPOP": {"SPOP",
		"key [count]",
		"Remove and return one or multiple random members from a set",
		cmdGroupSet,
		"1.0.0"},
	"SRANDMEMBER": {"SRANDMEMBER",
		"key [count]",
		"Get one or multiple random members from a set",
		cmdGroupSet,
		"1.0.0"},
	"SREM": {"SREM",
		"key member [member ...]",
		"Remove one or more members from a set",
		cmdGroupSet,
		"1.0.0"},
	"SSCAN": {"SSCAN",
		"key cursor [MATCH pattern] [COUNT count]",
		"Incrementally iterate Set elements",
		cmdGroupSet,
		"2.8.0"},
	"STRALGO": {"STRALGO",
		"LCS algo-specific-argument [algo-specific-argument ...]",
		"Run algorithms (currently LCS) against strings",
		cmdGroupString,
		"6.0.0"},
	"STRLEN": {"STRLEN",
		"key",
		"Get the length of the value stored in a key",
		cmdGroupString,
		"2.2.0"},
	"SUBSCRIBE": {"SUBSCRIBE",
		"channel [channel ...]",
		"Listen for messages published to the given channels",
		cmdGroupPubSub,
		"2.0.0"},
	"SUNION": {"SUNION",
		"key [key ...]",
		"Add multiple sets",
		cmdGroupSet,
		"1.0.0"},
	"SUNIONSTORE": {"SUNIONSTORE",
		"destination key [key ...]",
		"Add multiple sets and store the resulting set in a key",
		cmdGroupSet,
		"1.0.0"},
	"SWAPDB": {"SWAPDB",
		"index1 index2",
		"Swaps two Redis databases",
		cmdGroupServer,
		"4.0.0"},
	"SYNC": {"SYNC",
		"-",
		"Internal command used for replication",
		cmdGroupServer,
		"1.0.0"},
	"TIME": {"TIME",
		"-",
		"Return the current server time",
		cmdGroupServer,
		"2.6.0"},
	"TOUCH": {"TOUCH",
		"key [key ...]",
		"Alters the last access time of a key(s). Returns the number of existing keys specified.",
		cmdGroupGeneric,
		"3.2.1"},
	"TTL": {"TTL",
		"key",
		"Get the time to live for a key",
		cmdGroupGeneric,
		"1.0.0"},
	"TYPE": {"TYPE",
		"key",
		"Determine the type stored at key",
		cmdGroupGeneric,
		"1.0.0"},
	"UNLINK": {"UNLINK",
		"key [key ...]",
		"Delete a key asynchronously in another thread. Otherwise it is just as DEL, but non blocking.",
		cmdGroupGeneric,
		"4.0.0"},
	"UNSUBSCRIBE": {"UNSUBSCRIBE",
		"[channel [channel ...]]",
		"Stop listening for messages posted to the given channels",
		cmdGroupPubSub,
		"2.0.0"},
	"UNWATCH": {"UNWATCH",
		"-",
		"Forget about all watched keys",
		cmdGroupTransactions,
		"2.2.0"},
	"WAIT": {"WAIT",
		"numreplicas timeout",
		"Wait for the synchronous replication of all the write commands sent in the context of the current connection",
		cmdGroupGeneric,
		"3.0.0"},
	"WATCH": {"WATCH",
		"key [key ...]",
		"Watch the given keys to determine execution of the MULTI/EXEC block",
		cmdGroupTransactions,
		"2.2.0"},
	"XACK": {"XACK",
		"key group ID [ID ...]",
		"Marks a pending message as correctly processed, effectively removing it from the pending entries list of the consumer group. Return value of the command is the number of messages successfully acknowledged, that is, the IDs we were actually able to resolve in the PEL.",
		cmdGroupStream,
		"5.0.0"},
	"XADD": {"XADD",
		"key ID field value [field value ...]",
		"Appends a new entry to a stream",
		cmdGroupStream,
		"5.0.0"},
	"XCLAIM": {"XCLAIM",
		"key group consumer min-idle-time ID [ID ...] [IDLE ms] [TIME ms-unix-time] [RETRYCOUNT count] [force] [justid]",
		"Changes (or acquires) ownership of a message in a consumer group, as if the message was delivered to the specified consumer.",
		cmdGroupStream,
		"5.0.0"},
	"XDEL": {"XDEL",
		"key ID [ID ...]",
		"Removes the specified entries from the stream. Returns the number of items actually deleted, that may be different from the number of IDs passed in case certain IDs do not exist.",
		cmdGroupStream,
		"5.0.0"},
	"XGROUP": {"XGROUP",
		"[CREATE key groupname id-or-$] [SETID key groupname id-or-$] [DESTROY key groupname] [DELCONSUMER key groupname consumername]",
		"Create, destroy, and manage consumer groups.",
		cmdGroupStream,
		"5.0.0"},
	"XINFO": {"XINFO",
		"[CONSUMERS key groupname] [GROUPS key] [STREAM key] [HELP]",
		"Get information on streams and consumer groups",
		cmdGroupStream,
		"5.0.0"},
	"XLEN": {"XLEN",
		"key",
		"Return the number of entries in a stream",
		cmdGroupStream,
		"5.0.0"},
	"XPENDING": {"XPENDING",
		"key group [start end count] [consumer]",
		"Return information and entries from a stream consumer group pending entries list, that are messages fetched but never acknowledged.",
		cmdGroupStream,
		"5.0.0"},
	"XRANGE": {"XRANGE",
		"key start end [COUNT count]",
		"Return a range of elements in a stream, with IDs matching the specified IDs interval",
		cmdGroupStream,
		"5.0.0"},
	"XREAD": {"XREAD",
		"[COUNT count] [BLOCK milliseconds] STREAMS key [key ...] id [id ...]",
		"Return never seen elements in multiple streams, with IDs greater than the ones reported by the caller for each stream. Can block.",
		cmdGroupStream,
		"5.0.0"},
	"XREADGROUP": {"XREADGROUP",
		"GROUP group consumer [COUNT count] [BLOCK milliseconds] [NOACK] STREAMS key [key ...] ID [ID ...]",
		"Return new entries from a stream using a consumer group, or access the history of the pending entries for a given consumer. Can block.",
		cmdGroupStream,
		"5.0.0"},
	"XREVRANGE": {"XREVRANGE",
		"key end start [COUNT count]",
		"Return a range of elements in a stream, with IDs matching the specified IDs interval, in reverse order (from greater to smaller IDs) compared to XRANGE",
		cmdGroupStream,
		"5.0.0"},
	"XTRIM": {"XTRIM",
		"key MAXLEN [~] count",
		"Trims the stream to (approximately if '~' is passed) a certain size",
		cmdGroupStream,
		"5.0.0"},
	"ZADD": {"ZADD",
		"key [NX|XX] [CH] [INCR] score member [score member ...]",
		"Add one or more members to a sorted set, or update its score if it already exists",
		cmdGroupSortedSet,
		"1.2.0"},
	"ZCARD": {"ZCARD",
		"key",
		"Get the number of members in a sorted set",
		cmdGroupSortedSet,
		"1.2.0"},
	"ZCOUNT": {"ZCOUNT",
		"key min max",
		"Count the members in a sorted set with scores within the given values",
		cmdGroupSortedSet,
		"2.0.0"},
	"ZINCRBY": {"ZINCRBY",
		"key increment member",
		"Increment the score of a member in a sorted set",
		cmdGroupSortedSet,
		"1.2.0"},
	"ZINTERSTORE": {"ZINTERSTORE",
		"destination numkeys key [key ...] [WEIGHTS weight] [AGGREGATE SUM|MIN|MAX]",
		"Intersect multiple sorted sets and store the resulting sorted set in a new key",
		cmdGroupSortedSet,
		"2.0.0"},
	"ZLEXCOUNT": {"ZLEXCOUNT",
		"key min max",
		"Count the number of members in a sorted set between a given lexicographical range",
		cmdGroupSortedSet,
		"2.8.9"},
	"ZPOPMAX": {"ZPOPMAX",
		"key [count]",
		"Remove and return members with the highest scores in a sorted set",
		cmdGroupSortedSet,
		"5.0.0"},
	"ZPOPMIN": {"ZPOPMIN",
		"key [count]",
		"Remove and return members with the lowest scores in a sorted set",
		cmdGroupSortedSet,
		"5.0.0"},
	"ZRANGE": {"ZRANGE",
		"key start stop [WITHSCORES]",
		"Return a range of members in a sorted set, by index",
		cmdGroupSortedSet,
		"1.2.0"},
	"ZRANGEBYLEX": {"ZRANGEBYLEX",
		"key min max [LIMIT offset count]",
		"Return a range of members in a sorted set, by lexicographical range",
		cmdGroupSortedSet,
		"2.8.9"},
	"ZRANGEBYSCORE": {"ZRANGEBYSCORE",
		"key min max [WITHSCORES] [LIMIT offset count]",
		"Return a range of members in a sorted set, by score",
		cmdGroupSortedSet,
		"1.0.5"},
	"ZRANK": {"ZRANK",
		"key member",
		"Determine the index of a member in a sorted set",
		cmdGroupSortedSet,
		"2.0.0"},
	"ZREM": {"ZREM",
		"key member [member ...]",
		"Remove one or more members from a sorted set",
		cmdGroupSortedSet,
		"1.2.0"},
	"ZREMRANGEBYLEX": {"ZREMRANGEBYLEX",
		"key min max",
		"Remove all members in a sorted set between the given lexicographical range",
		cmdGroupSortedSet,
		"2.8.9"},
	"ZREMRANGEBYRANK": {"ZREMRANGEBYRANK",
		"key start stop",
		"Remove all members in a sorted set within the given indexes",
		cmdGroupSortedSet,
		"2.0.0"},
	"ZREMRANGEBYSCORE": {"ZREMRANGEBYSCORE",
		"key min max",
		"Remove all members in a sorted set within the given scores",
		cmdGroupSortedSet,
		"1.2.0"},
	"ZREVRANGE": {"ZREVRANGE",
		"key start stop [WITHSCORES]",
		"Return a range of members in a sorted set, by index, with scores ordered from high to low",
		cmdGroupSortedSet,
		"1.2.0"},
	"ZREVRANGEBYLEX": {"ZREVRANGEBYLEX",
		"key max min [LIMIT offset count]",
		"Return a range of members in a sorted set, by lexicographical range, ordered from higher to lower strings.",
		cmdGroupSortedSet,
		"2.8.9"},
	"ZREVRANGEBYSCORE": {"ZREVRANGEBYSCORE",
		"key max min [WITHSCORES] [LIMIT offset count]",
		"Return a range of members in a sorted set, by score, with scores ordered from high to low",
		cmdGroupSortedSet,
		"2.2.0"},
	"ZREVRANK": {"ZREVRANK",
		"key member",
		"Determine the index of a member in a sorted set, with scores ordered from high to low",
		cmdGroupSortedSet,
		"2.0.0"},
	"ZSCAN": {"ZSCAN",
		"key cursor [MATCH pattern] [COUNT count]",
		"Incrementally iterate sorted sets elements and associated scores",
		cmdGroupSortedSet,
		"2.8.0"},
	"ZSCORE": {"ZSCORE",
		"key member",
		"Get the score associated with the given member in a sorted set",
		cmdGroupSortedSet,
		"1.2.0"},
	"ZUNIONSTORE": {"ZUNIONSTORE",
		"destination numkeys key [key ...] [WEIGHTS weight] [AGGREGATE SUM|MIN|MAX]",
		"Add multiple sorted sets and store the resulting sorted set in a new key",
		cmdGroupSortedSet,
		"2.0.0"},
}
